version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '11787:80'
    container_name: wxcloud_miniapp4yima
    labels:
      - wxPort=11771
      - hostPort=11787
      - wxcloud=miniapp4yima
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    external:
      name: wxcb0
